# Module manifest for module 'Phelpers'
# Generated by: Lage Berger Jensen
# Generated on: 10.08.2021

@{
    RootModule        = 'Phelpers.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = 'b10b67ad-f17b-4831-8a65-52ead3b57621'
    Author            = 'Lage Berger Jensen'
    CompanyName       = ''
    Copyright         = '(c) 2021 Lage Berger Jensen. All rights reserved.'
    Description       = 'Collection of helpful functions'
    FunctionsToExport = @(
        'Get-PublicIp',
        'Get-AzureIpRange'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            LicenseUri = 'https://github.com/lagebj/Phelpers/blob/master/LICENSE'
            ProjectUri = 'https://github.com/lagebj/Phelpers'
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    DefaultCommandPrefix = 'Ph'
}
